apiVersion: v1
kind: Service
metadata:
  name: hello-spring-external-service
spec:
  selector:
    app: hello-spring
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31596  #accès fixe
  type: NodePort
